### ISSUE TITLE
Error in hclust(md, method = "ward.D2") : Invalid clustering method "

### ISSUE THREAD

**Issue by cdkodira** [yycunc/SAMEclustering#1]
I get this error " Error in hclust(md, method = "ward.D2") : Invalid clustering method "

when I run  this command-
cluster.result <- individual_clustering(inputTags = data_SAME$Zheng.expr, datatype = "count", 
                                        percent_dropout = 10, SC3 = TRUE, CIDR = TRUE, nPC.cidr = NULL, Seurat = TRUE, nPC.seurat = NULL, 
                                        resolution = 0.9, tSNE = TRUE, dimensions = 2, perplexity = 30, SIMLR = TRUE, diverse = TRUE, SEED = 123)

**Comment by yycunc** [comment]
Hi,

Thanks for interesting in our method. I think the issue occurs when you call CIDE for clustering. May I have some more details on your data? What is the cell number for the expression matrix?

**Comment by cdkodira** [comment]
I'm using your example file.
Thanks,
Dilip

cluster.results <- individual_clustering(inputTags = data_SAFE$Zheng.expr, datatype = "count", mt_filter = FALSE, CIDR = TRUE, nPC.cidr = NULL, Seurat = TRUE, nPC.seurat = NULL, resolution = 0.9,
                                         nGene_filter = FALSE, SC3 = TRUE, gene_filter = FALSE,
                                          tSNE = TRUE, dimensions = 3, perplexity = 30, SEED = 123)


Performing SC3 clustering...
Estimating k...
Setting SC3 parameters...
Calculating distances between the cells...
Performing transformations and calculating eigenvectors...
Performing k-means clustering...

Calculating consensus matrix...
Performing CIDR clustering...
Performing Seurat clustering...
Error in CreateSeuratObject(raw.data = inputTags, min.cells = 3, min.genes = 200,  :
  unused arguments (raw.data = inputTags, min.genes = 200)


________________________________

**Comment by yycunc** [comment]
Hi Dilip,

According to the error information, I think it occurs that you are using the latest Seurat version (v3 or higher), however, SAMEclustering works with Seurat v2. Now, the way to fix it is to run individual_clustering function with Seurat = FALSE, and run Seurat separately, and then combined the clustering outputs together for downstream cluster ensemble.

I also want to thank you for the comments. As more and more people use Seurat v3 now, I will update the individual_clustering function to make it compatible to Seurat v3.
